@base=http://localhost:4000/api/v1/auth

POST {{base}}/register
Content-Type: application/json

{
    "email": "mario.rossi@mail.com",
    "password": "m.rossi.pass",
    "firstName": "Mario",
    "lastName": "Rossi",
    "phone": "3356768990",
    "birthDate": "06/03/1985"
}

###
POST {{base}}/login
Content-Type: application/json

{
    "email": "iolanda.anile@gmail.com",
    "password": "passwordSicura12345"
}