@base=http://localhost:4000/api/v1/cart
@tokenUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjEyYmU4YTliZDhmNjJmNGRmNTJhZiIsImlhdCI6MTc2MDYzNTk5NSwiZXhwIjoxNzYzMjI3OTk1fQ.1oA0ZSKJwpCdKQn3_AyI88ExX6CZ1VZ7ZnqGfvyRtHU
@tokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWJjNTZhMTkzM2FjZTY5NzQyZmY4NyIsImlhdCI6MTc2MDI4NDU1OCwiZXhwIjoxNzYyODc2NTU4fQ.ZU_7se0QUDofkwMCMMh2LA5d0xfEvcmpIB7zV2ahh18

GET {{base}}/
Authorization: Bearer {{tokenUser}}

###
POST {{base}}/items
Content-Type: application/json
Authorization: Bearer {{tokenUser}}

{
    "itemId": "68f12f84384abe1691e7dc12",
    "variantId": "68f13049384abe1691e7dc30",
    "quantity": 2
}


###
PUT {{base}}/items/68f12f84384abe1691e7dc12/68f13049384abe1691e7dc30
Content-Type: application/json
Authorization: Bearer {{tokenUser}}

{
    "quantity": 5
}


###
DELETE {{base}}/items/68f12f84384abe1691e7dc12/68f13049384abe1691e7dc30
Content-Type: application/json
Authorization: Bearer {{tokenUser}}